# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
   # pool:
    #  name: Default
     # demands: 
     # - Agent.Name -equals selfhostedagent
    pool: 
     vmImage: ubuntu-latest

    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        buildContext: '$(Build.SourcesDirectory)/complexapp'
        command: build
        dockerfile: '$(Build.SourcesDirectory)/complexapp/dockerfile'
        tags: |
         $(tag)
    